config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: %i[new create show]
  resources :products do
    resources :transactions, only: :create
  end
  resources :reviews, only: %i[new create destroy]
  resources :transactions, only: :destroy
  get 'transactions/:id/confirmation', to: 'transactions#confirmation', as: 'confirmation'
  get 'dashboard', to: 'pages#user_dash', as: 'dashboard'
  get 'mydashboard', to: 'products#user_dashboard', as: 'mydashboard'
  get 'basket', to: 'transactions#basket', as: 'basket'
  get 'payment', to: 'transactions#confirmation', as: 'payment'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/?lang=en"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-text">
  <p>Contact address: Unit 13, 138 Kingsland Road, London E2 8DY</p>
  <p>© 2022 Le Wagon, Inc. All rights reserved.</p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="hello">
  <div class="container-fluid">
    <div style="width=30%">
      <%= link_to "/", class: "navbar-brand" do %>
        <img src="https://res.cloudinary.com/dxleey3up/image/upload/v1670325589/development/logolw_e0fijt.png" class="logo">
      <% end %>
    </div>

    <div class=<%= current_page?(root_path) ? "d-none" : "wrap" %>>
      <div class="search" style="width=30%">
          <%= form_with url: products_path, method: :get, class: "d-flex flex-column justify-content-center" do %>
            <div class="d-flex" style="height: 35px !important;">
              <%= text_field_tag :buy,
                params[:buy],
                class: "searchTerm",
                placeholder: "Browse for items"
              %>
              <%= submit_tag "Search", class: "searchButton" %>
            </div>
          <% end %>
      </div>
    </div>

    <div style="width=30%">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>

  </div>

    <% if user_signed_in? %>
      <%= link_to "All Products", products_path, class: "nav-link #{"active" if current_page?('/products')}" %>
      <%= link_to "Dashboard", mydashboard_path, class: "nav-link #{"active" if current_page?('/myproducts')}" %>
      <%= link_to "Basket", basket_path, class: "nav-link #{"active" if current_page?('/basket')}" %>
       <ul style="list-style:none;">
        <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          </li>
        </ul>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link #{"active" if current_page?('/users/sign_in')}"%>
    <% end %>
</div>
<%#
    <div class="offcanvas offcanvas-end offcanvas-size-sm" data-bs-backdrop="static" tabindex="-1" id="staticBackdrop" aria-labelledby="staticBackdropLabel">
      <div class="offcanvas-header">
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <div>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        <%# </div>
      </div>
    </div> %>