config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: %i[new create show]
  resources :products do
    resources :transactions, only: :create
  end
  resources :reviews, only: %i[new create destroy]
  resources :transactions, only: :destroy
  get 'transactions/:id/confirmation', to: 'transactions#confirmation', as: 'confirmation'
  get 'dashboard', to: 'pages#user_dash', as: 'dashboard'
  get 'mydashboard', to: 'products#user_dashboard', as: 'mydashboard'
  get 'basket', to: 'transactions#basket', as: 'basket'
  get 'payment', to: 'transactions#confirmation', as: 'payment'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_product, only: :create
  before_action :set_transaction, only: :destroy

  def create
    @transaction = Transaction.new(user_id: current_user.id, product_id: @product.id)
    if @transaction.save!

    else
      render 'products/show', status: :unprocessable_entity
    end
  end

  def basket
    @transactions = Transaction.where(user_id: current_user.id).reject { |transaction| transaction.product.is_sold}
    @total_amount = @transactions.map { |transaction| transaction.product.price.round(2) }.sum.round(2)
    @order = Order.new(user: current_user, total_amount: @total_amount)

    if !@transactions.empty?
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          price_data: {
            currency: 'gbp',
            unit_amount: (@total_amount * 100).to_i,
            product_data: {
              name: 'Your Order',
              description: ' ',
              images: []
            }
          },
          quantity: 1
        }],
        mode: 'payment',
        success_url: Rails.env.production? ? "http://www.lewagonmarketplace.co/payment" : "http://localhost:3000/payment",
        cancel_url: Rails.env.production? ? "http://www.lewagonmarketplace.co/basket" : "http://localhost:3000/basket"
      )

      @order.update(checkout_session_id: session.id)
    end
  end

  def destroy
    @transaction.destroy
    redirect_to basket_path, status: :see_other
  end

  def checkout
    @transactions = Transaction.where(user_id: current_user.id)
  end

  def confirmation
    @products = current_user.transactions.map(&:product).reject(&:is_sold)
    current_user.transactions.map(&:product).reject(&:is_sold).each do |product|
      product.update(is_sold: true)
    end
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end
end

app/views/transactions/basket.html.erb
<div class="basket-container mt-3">
  <div class="d-flex justify-content-center">
    <h1>Basket</h1>
  </div>

  <div class="d-flex justify-content-space-around">
    <div class="basket <%= "d-none" if @transactions.empty? %>">
      <% @transactions.each do |transaction| %>
        <div class="basket-card d-flex mt-3">
            <%= cl_image_tag transaction.product.photos.first.key, width: 150, height: 150, crop: :fill %>
            <ul style="list-style:none; width: 100%;" class="d-flex justify-content-between mt-1">
              <div style="width: 75%" class="d-flex flex-column align-items-start justify-content-between mt-2">
                <li class="item-name fw-bold fs-6"><%= transaction.product.item %></li>
                <li class="fs-6"> £<%= '%.2f' % transaction.product.price %></li>
              </div>
              <div style="width: 25%">
                <div class="d-flex justify-content-end pe-3">
                  <%= link_to 'x', transaction_path(transaction), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none text-secondary" %>
                </div>
              </div>
            </ul>
        </div>
      <%end%>
    </div>

    <div class="total pt-3 mt-3 d-flex flex-column sticky-top" style="width: 40%;" >
      <div class="d-flex justify-content-center">
        <p class="border-bottom items-name" style="width: 80%;">Order summary</p>
      </div>
      <div class="d-flex justify-content-around">
        <p>Total (<%= @transactions.count == 1 ? "#{@transactions.count} item" : "#{@transactions.count} items" %>)</p>
        £<%= "%.2f" % @transactions.map { |transaction| transaction.product.price.round(2) }.sum %>
      </div>

      <button class="buynow-button text-light my-3" id="pay">Checkout</button>
    </div>
  </div>
</div>



<script src="https://js.stripe.com/v3/"></script>
<script>
  paymentButton = document.getElementById('pay');
  paymentButton.addEventListener('click', () => {
    const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
    stripe.redirectToCheckout({
      sessionId: '<%= @order.checkout_session_id %>'
    });
  });
</script>






<%# <% link_to "Buy now", root_path, method: :get %>

app/views/transactions/checkout.html.erb
<h1></h1>



<% link_to "Buy now", root_path, method: :get, data: {turbo_method: :get, turbo_confirm: "Your purchase was successful! You will now be redirected to the homepage, Do not refresh this page"} %>

<script src="https://cdn01.jotfor.ms/static/prototype.forms.js?3.3.37728" type="text/javascript"></script>
<script src="https://cdn02.jotfor.ms/static/jotform.forms.js?3.3.37728" type="text/javascript"></script>
<script type="text/javascript">	JotForm.newDefaultTheme = true;
	JotForm.extendsNewTheme = false;
	JotForm.singleProduct = false;
	JotForm.newPaymentUIForNewCreatedForms = true;
	JotForm.newPaymentUI = true;
	JotForm.clearFieldOnHide="disable";
	JotForm.submitError="jumpToFirstError";

	JotForm.init(function(){
	/*INIT-START*/
if (window.JotForm && JotForm.accessible) $('input_6').setAttribute('tabindex',0);
if (window.JotForm && JotForm.accessible) $('input_7').setAttribute('tabindex',0);
if (window.JotForm && JotForm.accessible) $('input_8').setAttribute('tabindex',0);
      JotForm.alterTexts(undefined);
	/*INIT-END*/
	});

   JotForm.prepareCalculationsOnTheFly([null,{"name":"heading","qid":"1","text":"Checkout","type":"control_head"},{"name":"submit2","qid":"2","text":"Submit","type":"control_button"},{"description":"","name":"name","qid":"3","text":"Name","type":"control_fullname"},null,null,{"description":"","name":"cardNumber","qid":"6","subLabel":"","text":"Card number","type":"control_textbox"},{"description":"","name":"expiryDate","qid":"7","subLabel":"","text":"Expiry Date (MM\u002FYY)","type":"control_textbox"},{"description":"","name":"cvvCode","qid":"8","subLabel":"","text":"CVV Code","type":"control_textbox"}]);
   setTimeout(function() {
JotForm.paymentExtrasOnTheFly([null,{"name":"heading","qid":"1","text":"Checkout","type":"control_head"},{"name":"submit2","qid":"2","text":"Submit","type":"control_button"},{"description":"","name":"name","qid":"3","text":"Name","type":"control_fullname"},null,null,{"description":"","name":"cardNumber","qid":"6","subLabel":"","text":"Card number","type":"control_textbox"},{"description":"","name":"expiryDate","qid":"7","subLabel":"","text":"Expiry Date (MM\u002FYY)","type":"control_textbox"},{"description":"","name":"cvvCode","qid":"8","subLabel":"","text":"CVV Code","type":"control_textbox"}]);}, 20);
</script>
<style type="text/css">@media print{.form-section{display:inline!important}.form-pagebreak{display:none!important}.form-section-closed{height:auto!important}.page-section{position:initial!important}}</style>
<link type="text/css" rel="stylesheet" href="https://cdn01.jotfor.ms/themes/CSS/5e6b428acc8c4e222d1beb91.css?themeRevisionID=63763808623532087895e4de"/>
<link type="text/css" rel="stylesheet" href="https://cdn02.jotfor.ms/css/styles/payment/payment_styles.css?3.3.37728" />
<link type="text/css" rel="stylesheet" href="https://cdn03.jotfor.ms/css/styles/payment/payment_feature.css?3.3.37728" />
<style type="text/css" id="form-designer-style">
    /* Injected CSS Code */
.form-label.form-label-auto {

        display: inline-block;
        float: left;
        text-align: left;

      }
    /* Injected CSS Code */
</style>

<form class="jotform-form" action="https://submit.jotformeu.com/submit/223352491697060/" method="post" name="form_223352491697060" id="223352491697060" accept-charset="utf-8" autocomplete="on"><input type="hidden" name="formID" value="223352491697060" /><input type="hidden" id="JWTContainer" value="" /><input type="hidden" id="cardinalOrderNumber" value="" />
  <div role="main" class="form-all mb-0">
    <style>
      .form-all:before
      {
        background: none;
      }
    </style>
    <ul class="form-section page-section">
      <li id="cid_1" class="form-input-wide" data-type="control_head">
        <div class="form-header-group  header-large">
          <div class="header-text httal htvam">
            <h1 id="header_1" class="form-header" data-component="header">Checkout</h1>
          </div>

        </div>
      </li>
      <li class="form-line" data-type="control_fullname" id="id_3"><label class="form-label form-label-left form-label-auto" id="label_3" for="first_3"> Name </label>
        <div id="cid_3" class="form-input" data-layout="full">
          <div data-wrapper-react="true"><span class="form-sub-label-container" style="vertical-align:top" data-input-type="first"><input type="text" id="first_3" name="q3_name[first]" class="form-textbox" data-defaultvalue="" autoComplete="section-input_3 given-name" size="10" value="" data-component="first" aria-labelledby="label_3 sublabel_3_first" /> <label class="form-sub-label" for="first_3" id="sublabel_3_first" style="min-height:13px" aria-hidden="false">First Name</label></span><span class="form-sub-label-container" style="vertical-align:top" data-input-type="last"><input type="text" id="last_3" name="q3_name[last]" class="form-textbox" data-defaultvalue="" autoComplete="section-input_3 family-name" size="15" value="" data-component="last" aria-labelledby="label_3 sublabel_3_last" /> <label class="form-sub-label" for="last_3" id="sublabel_3_last" style="min-height:13px" aria-hidden="false">Last Name</label></span></div>
        </div>
      </li>
      <li class="form-line" data-type="control_textbox" id="id_6"><label class="form-label form-label-left form-label-auto" id="label_6" for="input_6"> Card number </label>
        <div id="cid_6" class="form-input" data-layout="half"> <input type="text" id="input_6" name="q6_cardNumber" data-type="input-textbox" class="form-textbox" data-defaultvalue="" style="width:310px" size="310" value="" data-component="textbox" aria-labelledby="label_6" /> </div>
      </li>
      <li class="form-line" data-type="control_textbox" id="id_7"><label class="form-label form-label-left form-label-auto" id="label_7" for="input_7"> Expiry Date (MM/YY) </label>
        <div id="cid_7" class="form-input" data-layout="half"> <input type="text" id="input_7" name="q7_expiryDate" data-type="input-textbox" class="form-textbox" data-defaultvalue="" style="width:310px" size="310" value="" data-component="textbox" aria-labelledby="label_7" /> </div>
      </li>
      <li class="form-line" data-type="control_textbox" id="id_8"><label class="form-label form-label-left form-label-auto" id="label_8" for="input_8"> CVV Code </label>
        <div id="cid_8" class="form-input" data-layout="half"> <input type="text" id="input_8" name="q8_cvvCode" data-type="input-textbox" class="form-textbox" data-defaultvalue="" style="width:310px" size="310" value="" data-component="textbox" aria-labelledby="label_8" /> </div>
      </li>
      <li style="display:none">Should be Empty: <input type="text" name="website" value="" /></li>
    </ul>
      <div class="subtotal">
        <p>Total to pay now: £<%= Transaction.basket_total(@transactions) %></p>
      </div>
  </div>
  <div class="checkout-button mt-3">
      <%= link_to "Buy now", root_path, class: "text-light", data: {turbo_method: :get, turbo_confirm: "Your purchase was successful! You will now be redirected to the homepage, Do not refresh this page"} %>
    </div>
  <script>
    JotForm.showJotFormPowered = "new_footer";
  </script>
  <script>
    JotForm.poweredByText = "Powered by Jotform";
  </script><input type="hidden" class="simple_spc" id="simple_spc" name="simple_spc" value="223352491697060" />
  <script type="text/javascript">
    var all_spc = document.querySelectorAll("form[id='223352491697060'] .si" + "mple" + "_spc");
    for (var i = 0; i < all_spc.length; i++)
    {
      all_spc[i].value = "223352491697060-223352491697060";
    }
  </script>



</form><script type="text/javascript">JotForm.ownerView=true;</script><script type="text/javascript">JotForm.forwardToEu=true;</script><script src="https://cdn.jotfor.ms//js/vendor/smoothscroll.min.js?v=3.3.37728"></script>
<script src="https://cdn.jotfor.ms//js/errorNavigation.js?v=3.3.37728"></script>

app/views/transactions/confirmation.html.erb
<div class="d-flex flex-column justify-content-center" style="width: 30%; margin: 0 auto;">
  <h1 class="text-center mt-5 border-3 pb-2">Thank you!</h1>
  <div class="border mt-4 total py-4">
    <h3 class="text-center mt-2 fw-bolder fs-2">Order Summary</h3>
    <div class="d-flex justify-content-center">
      <p class="border-bottom" style="width: 80%"></p>
    </div>
    <div class="d-flex flex-column justify-content-center align-items-center mt-4">
      <% @products.each do |product| %>
        <div class="d-flex justify-content-between"  style="width: 50%">
          <p><%= product.item %></p>
          <p>£<%= '%.2f' % product.price %></p>
        </div>
      <% end %>
      <div class="d-flex justify-content-between mt-4 fs-4 fw-bold" style="width: 70%">
        <p>Total paid</p>
        <p>£<%= '%.2f' % @products.map(&:price).sum %></p>
      </div>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <%= link_to "View Orders", mydashboard_path(active_tab: "orders"), class: "button me-3 fs-6" %>
      <%= link_to "Back to Homepage", root_path, class: "button fs-6" %>
    </div>
  </div>
</div>