config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: %i[new create show]
  resources :products do
    resources :transactions, only: :create
  end
  resources :reviews, only: %i[new create destroy]
  resources :transactions, only: :destroy
  get 'transactions/:id/confirmation', to: 'transactions#confirmation', as: 'confirmation'
  get 'dashboard', to: 'pages#user_dash', as: 'dashboard'
  get 'mydashboard', to: 'products#user_dashboard', as: 'mydashboard'
  get 'basket', to: 'transactions#basket', as: 'basket'
  get 'payment', to: 'transactions#confirmation', as: 'payment'
end

app/models/product.rb
class Product < ApplicationRecord
  CATEGORY = ['Bedroom', 'Kitchenware', 'Living Room & Garden', 'Clothing', 'Electronics', 'Sports & Leisure', 'Other']
  belongs_to :user
  has_many :transactions
  validates :item, :price, :photos, :category, presence: true
  validates :description, length: { minimum: 6, too_short: "%<count> characters is the minimum allowed" }
  has_many_attached :photos
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show destroy confirm reject]
  before_action :set_user, only: %i[index show destroy create]

  def index
    if params[:category].present? && params[:buy].present?
      @pagy, @products = pagy(Product.where(category: params[:category]).where("item ILIKE ?", "%#{params[:buy]}%").where.not(user_id: @user.id).where(is_sold: false))
    elsif params[:category].present? && params[:buy].nil?
      @pagy, @products = pagy(Product.where(category: params[:category]).where.not(user_id: @user.id).where(is_sold: false))
    elsif params[:buy].present? && params[:category].nil?
      @pagy, @products = pagy(Product.where("item ILIKE ?", "%#{params[:buy]}%").where.not(user_id: @user.id).where(is_sold: false))
    else
      @pagy, @products = pagy(Product.where.not(user_id: @user.id).where(is_sold: false))
    end
  end

  def new
    @product = Product.new
  end

  def show
  end

  def create
    @product = Product.new(product_params)
    @product.user = @user
    if @product.save!
      redirect_to mydashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to mydashboard_path, status: :see_other
  end

  def my_products
    @listed_products = Product.where(user: current_user, is_sold: false)
    @sold_products = Product.where(user: current_user, is_sold: true)
  end

  def purchased_products
    unfinished_transactions = Transaction.where(user: current_user).where('is_delivered = ?', false)
    unfinished_transactions_ids = unfinished_transactions.map { |transaction| transaction.product.id }
    @purchased_products = Product.where(id: unfinished_transactions_ids, is_sold: true)
  end

  def user_dashboard
    @listed_products = Product.where(user: current_user, is_sold: false)
    @sold_products = Product.where(user: current_user, is_sold: true)
    unfinished_transactions = Transaction.where(user: current_user).where('is_delivered = ?', false)
    unfinished_transactions_ids = unfinished_transactions.map { |transaction| transaction.product.id }
    @purchased_products = Product.where(id: unfinished_transactions_ids, is_sold: true)
  end

  private

  def product_params
    params.require(:product).permit(:item, :description, :price, :category, photos: [])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/views/products/_my_products.html.erb
<div class="container3">
  <h1 class= "d-flex justify-content-center">Listed Products</h1>
  <% if listed_products.empty? %>
    <div>
      <p class="d-flex justify-content-center">
      <%="You're yet to list any products!"%></p>
    </div>
  <% else %>
    <div class="d-flex justify-content-center mt-3">
      <div class="basket d-flex flex-wrap <%= listed_products.count > 3 ? "justify-content-start" : "justify-content-center" %>">
        <% listed_products.each do |product| %>
          <%= link_to product_path(product), class: "text-decoration-none text-dark" do %>
            <div class="card-product mt-3 mx-0 width-50%">
              <%= cl_image_tag product.photos.first.key, width: 400, height: 350, crop: :fill %>
              <ul style="list-style:none; width: 100%;" class="d-flex justify-content-between mt-1 product-card-info">
                <div style="width: 55%" class="d-flex flex-column align-items-start justify-content-between mt-1 ms-3">
                  <li class="item-name fw-bold fs-5"><%= product.item %></li>
                  <li> £<%= '%.2f' % product.price %></li>
                </div>
              </ul>
            </div>
          <%end%>
          <%= link_to 'X', product_path(product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none text-secondary m-0 p-0", id: "delete-x" %>
        <%end%>
      </div>
    </div>
  <%end%>
</div>

app/views/products/_product.html.erb
<div class="indexcard col-sm-12 col-lg-3 mb-5">
  <%= link_to product, class: 'text-decoration-none text-dark' do %>
    <%= cl_image_tag product.photos.first.key, width: 350, height: 250, crop: :fill %>

    <div class="yo bg-white mb-4" style="height: 120px">
      <div class="w-full d-flex justify-content-around">
        <h3 class="item-namefont-normal flex-fill mt-2 px-2"><%= product.item %></h3>
      </div>
      <div class="noHover d-flex mb-2">
        <div class="d-flex align-items-center" >
          <%= cl_image_tag product.user.photo.key, style: "height: 50px; width: 50px;", class: "rounded" %>
          <p class="seller text-gray-500 text-sm p-1"style="margin-block-end: 0; margin-block-start: 0;"><%= product.user.name %></p>
        </div>
        <h5 class="fontw-bold ms-auto p-2">£<%= '%.2f' % product.price %></h5>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_purchased.html.erb
<div class="col-lg-4">
  <%= link_to product_path(product), class: "text-decoration-none" do %>
    <div class="card-product3 d-flex" >
      <%= cl_image_tag product.photos.first.key, width: 400, height: 350, crop: :fill %>
      <div class="ms-3 text-dark">
        <%= product.item %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_purchased_products.html.erb
<div class="container3">
  <h1 class= "d-flex justify-content-center">Orders</h1>
    <% if purchased_products.empty? %>
      <div>
        <p class="d-flex justify-content-center">
        <%="You're yet to make any purchases!"%></p>
      </div>
    <% else %>
      <div class="d-flex justify-content-center mt-3">
        <div class="basket d-flex flex-wrap <%= purchased_products.count > 3 ? "justify-content-start" : "justify-content-center" %>">
          <% purchased_products.each do |product| %>
            <%= link_to product_path(product), class: "text-decoration-none text-dark" do %>
              <div class="card-product mt-3 width-50%">
                <%= cl_image_tag product.photos.first.key, width: 400, height: 350, crop: :fill %>
                <ul style="list-style:none; width: 100%;" class="d-flex justify-content-between mt-1 product-card-info">
                  <div style="width: 55%" class="d-flex flex-column align-items-start justify-content-between mt-1 ms-3">
                    <li class="item-name fw-bold fs-5"><%= product.item %></li>
                    <li> £<%= '%.2f' % product.price %></li>
                  </div>
                </ul>
              </div>
            <%end%>
          <%end%>
        </div>
      </div>
    <%end%>
</div>

app/views/products/_sold_products.html.erb
<div class="container3">
  <h1 class= "d-flex justify-content-center">Sold Products</h1>
  <% if sold_products.empty? %>
    <div>
      <p class="d-flex justify-content-center">
      <%="You're yet to sell any items!"%></p>
    </div>
  <% else %>
    <div class="d-flex justify-content-center mt-3">
      <div class="basket d-flex flex-wrap <%= sold_products.count > 3 ? "justify-content-start" : "justify-content-center" %>">
        <% sold_products.each do |product| %>
          <%= link_to product_path(product), class: "text-decoration-none text-dark" do %>
            <div class="card-product mt-3 width-50%">
              <%= cl_image_tag product.photos.first.key, width: 400, height: 350, crop: :fill %>
              <ul style="list-style:none; width: 100%;" class="d-flex justify-content-between mt-1 product-card-info">
                <div style="width: 55%" class="d-flex flex-column align-items-start justify-content-between mt-1 ms-3">
                  <li class="item-name fw-bold fs-5"><%= product.item %></li>
                  <li> £<%= '%.2f' % product.price %></li>
                </div>
              </ul>
            </div>
          <%end%>
        <%end%>
      </div>
    </div>
  <%end%>
</div>

app/views/products/index.html.erb
<div class="d-flex justify-content-center mt-3">
  <h1> All Products available for sale <h1>
</div>

<div class="d-flex justify-content-center mb-4">
  <%= link_to "Add a new product", new_product_path, class: "button"  %>
</div>


<div class="index-container d-flex justify-content-between mt-3">
  <div class="row d-flex justify-content-between">

    <% @products.each do |product| %>
      <%= render product, product: product%>
    <%end%>
  </div>
</div>

<div class="d-flex justify-content-center px-3">
  <% link = pagy_link_proc(@pagy, link_extra: 'class="page-link"') -%>
  <%#                            -%><nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
  <%#                            -%>  <ul class="pagination">
  <% if @pagy.prev                -%>    <li class="page-item prev"><%== link.call(@pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
  <% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
  <% end                         -%>
  <% @pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
  <%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link.call(item) %></li>
  <%   elsif item.is_a?(String)  -%>    <li class="page-item active bg-dark"><%== link.call(item) %></li>
  <%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
  <%   end                       -%>
  <% end                         -%>
  <% if @pagy.next                -%>    <li class="page-item next"><%== link.call(@pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
  <% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
  <% end                         -%>
  <%#                            -%>  </ul>
  <%#                            -%></nav>
</div>

app/views/products/my_products.html.erb
<div class="container3 min-height">
  <h1 class= "d-flex justify-content-center border-bottom border-2">My Products</h1>
  <h2 class= "d-flex justify-content-center border-bottom border-2">Listed Products</h2>
  <div class="d-flex justify-content-center">
    <%= link_to "Add a new product", new_product_path, class: "button"  %>
  </div>
  <% if @listed_products.empty? %>
    <div>
      <p class="d-flex justify-content-center">
      <%="You're yet to list any products!"%></p>
    </div>
  <% else %>
    <div class="d-flex justify-content-center mt-3">
      <div class="basket d-flex justify-content-center" style="width: 60%;">
        <% @listed_products.each do |product| %>
          <%= link_to product_path(product), class: "text-decoration-none text-dark" do %>
            <div class="card-product mt-3">
              <%= cl_image_tag product.photos.first.key, width: 400, height: 350, crop: :fill %>
              <ul style="list-style:none; width: 100%;" class="d-flex justify-content-between mt-1 product-card-info">
                <div style="width: 55%" class="d-flex flex-column align-items-start justify-content-between mt-1 ms-3">
                  <li class="item-name"><%= product.item %></li>
                  <li> £<%= '%.2f' % product.price %></li>
                </div>
              </ul>
            </div>
          <%end%>
            <div class="pe-3">
              <%= link_to 'X', product_path(product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none text-secondary mr-0", id: "delete-x" %>
            </div>
        <%end%>
      </div>
    </div>
  <%end%>

  <div class="listed d-flex justify-content-center border-bottom border-2">
    <h2 class="sold">Sold Products</h2>
  </div>

  <% if @sold_products.empty? %>
    <div class="d-flex justify-content-center">
      <p>You're yet to sell any items!</p>
    </div>
  <% else %>
    <div class="d-flex justify-content-center mt-3">
      <div class="basket d-flex justify-content-center" style="width: 60%;">
        <% @sold_products.each do |product| %>
          <%= link_to product_path(product), class: "text-decoration-none text-dark" do %>
            <div class="card-product mt-3">
              <%= cl_image_tag product.photos.first.key, width: 400, height: 350, crop: :fill %>
              <ul style="list-style:none; width: 100%;" class="d-flex justify-content-between mt-1 product-card-info">
                <div style="width: 55%" class="d-flex flex-column align-items-start justify-content-between mt-1 ms-3">
                  <li class="item-name"><%= product.item %></li>
                  <li> £<%= '%.2f' % product.price %></li>
                </div>
              </ul>
            </div>
          <%end%>
            <div class="pe-3">
              <%= link_to 'X', product_path(product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none text-secondary mr-0", id: "delete-x" %>
            </div>
        <%end%>
      </div>
    </div>
  <%end%>
</div>

app/views/products/new.html.erb
<div class="min-height">


  <h1 class="d-flex justify-content-center mt-3">List a new product</h1>
  <p class="new-text d-flex justify-content-center my-3">Simply fill out the form below to list a new item to sell</p>


  <div class="newform d-flex justify-content-center">
    <%= simple_form_for @product do |f| %>
      <%= f.input :item, label: 'Product name:' %>

      <%= f.input :description, label: 'Brief description and condition of the product:' %>
      <%= f.input :category, collection: Product::CATEGORY %>
      <%= f.input :price, label: 'Set your price', placeholder: "£" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true }, label: "Image Upload (minimum of 3)" %>
      <div class="d-flex justify-content-center text-center">
        <%= f.button :submit, 'List Product', class: "list-button d-flex justify-content-center p-3" %>
      </div>
    <% end %>
  </div>

</div>

app/views/products/purchased_products.html.erb
<div class="d-flex justify-content-center">

  <div class="container3 mt-3 justify-content-center" style="width: 60%;">
    <% if @purchased_products.empty? %>
      <div class="empty">
        <h2 class="d-flex justify-content-center"><%="You're yet to make any purchases!"%></h2>
      </div>
    <% else %>
      <h1 class="d-flex justify-content-center border-bottom border-3 mb-5 pb-4 mt-3">My Products</h1>
      <div class="listed" >
        <h2 class="d-flex justify-content-center mb-3">Purchases</h2>
      </div>
      <div class="row">
        <% @purchased_products.each do |product| %>
          <%= render "purchased", product: product %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<% content_for :meta_title, "#{@product.item} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @product.description %>
<% content_for :meta_image, cl_image_path(@product.photos.first.key) %>

<div class=" mt-3">

  <div class="show">
    <h1><%= @product.item %></h1>
  </div>

  <div class="container d-flex justify-content-around" style="width: 100%;">
    <div class="card-container">
      <div style="width: 100%;">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="false">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= cl_image_tag @product.photos.first.key, class:"d-block", width: 700, height: 350, crop: :fill, gravity: :auto %>
            </div>
            <div class="carousel-item">
              <%= cl_image_tag @product.photos.second.key, class:"d-block", width: 700, height: 350, crop: :fill, gravity: :auto %>
            </div>
            <div class="carousel-item">
              <%= cl_image_tag @product.photos.third.key, class:"d-block", width: 700, height: 350, crop: :fill, gravity: :auto %>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="container d-flex justify-content-around" style="width: 749px">
    <div class="d-flex justify-content-center">
      <div class="card-product1 mb-4 px-3" style="min-heigh: 265px">
        <h4 class="product-name"><%= @product.description %></h4>
        <%# <div> %>
          <div class="seller-avatar d-flex justify-content-between align-items-end mt-5">
            <div class="d-flex justify-content-start align-items-center">
              <%= cl_image_tag @product.user.photo.key, class: "show-rounded2 me-3" %>
              <%=  link_to "https://lewagon-alumni.slack.com/team/#{@product.user.slack_id}", class: "user-info align-text-center text-decoration-none" do %>
                <h4 class="d-flex align-item-center"><%= "#{@product.user.name} (##{@product.user.batch})"%></h4>
              <% end %>
            </div>
            <h4 class="price1 d-flex align-items-end fw-bold fs-4 mt-3">£<%= '%.2f' % @product.price %></h4>
          </div>
          <% unless @product.user.id == current_user.id %>
            <div class="basket-b d-flex justify-content-center" data-controller="confirm">
              <%= button_to "Add to basket", product_transactions_path(@product), id: :confirm, method: :post, class:"button" %>
            </div>
          <% end %>
        <%# </div> %>
      </div>
    </div>
  </div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Success!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Succesfully added to basket!
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <p class="button"><%= link_to "Go to Basket", basket_path, class: "text-decoration-none text-light" %></p>
        <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button> %>
        <%= link_to "Continue Shopping", products_path, class: "button" %>
        <%# <button type="button" class="btn btn-primary">Save changes</button> %>
      </div>
    </div>
  </div>
</div>

</div>

app/views/products/user_dashboard.html.erb
<div class="container3">
  <ul class="nav nav-pills mb-3 d-flex justify-content-between align-items-center" id="pills-tab" role="tablist">
    <div class="d-flex justify-content-start">
      <li class="nav-item" role="presentation">
        <button class="nav-link <%= "active" if params[:active_tab] == "listed" || params[:active_tab].nil? %>" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
          Listed
        </button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link <%= "active" if params[:active_tab] == "sold" %>" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
          Sold
        </button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link <%= "active" if params[:active_tab] == "orders" %>" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">
          Orders
        </button>
      </li>
    </div>
    <li>
      <div class="d-flex justify-content-center">
        <%= link_to "Add a new product", new_product_path, class: "button"  %>
      </div>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade <%= "show active" if params[:active_tab] == "listed" || params[:active_tab].nil? %>" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <%= render "products/my_products", listed_products: @listed_products %>
    </div>
    <div class="tab-pane fade <%= "show active" if params[:active_tab] == "sold" %>" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <%= render "products/sold_products", sold_products: @sold_products %>
    </div>
    <div class="tab-pane fade <%= "show active" if params[:active_tab] == "orders" %>" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
      <%= render "products/purchased_products", purchased_products: @purchased_products %>
    </div>
  </div>
</div>